--<ScriptOptions statementTerminator=";"/>

--Script to create employee table

DROP TABLE "EMPLOYEE";
CREATE TABLE "EMPLOYEE" (
		"EMPLOYEEID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"FIRST_NAME" VARCHAR(20 OCTETS) NOT NULL, 
		"MIDDLE_NAME" VARCHAR(20 OCTETS), 
		"LAST_NAME1" VARCHAR(20 OCTETS) NOT NULL, 
		"LAST_NAME2" VARCHAR(20 OCTETS), 
		"BIRTH_DATE" DATE, 
		"HIRING_DATE" DATE, 
		"ROLE_NAME" VARCHAR(128 OCTETS), 
		"COMMENTS" LONG VARCHAR
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "SQL150309164132810" PRIMARY KEY
	("EMPLOYEEID");


