--<ScriptOptions statementTerminator=";"/>

--Script to create events table

DROP TABLE "EVENTS";
CREATE TABLE "EVENTS" (
		"EVENT_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE NO CACHE),
		"OBJECT_KEY" VARCHAR(80) NOT NULL,
		"OBJECT_VERB" VARCHAR(40) NOT NULL,
		"OBJECT_NAME" VARCHAR(20),
		"EVENT_PRIORITY" INTEGER,
		"EVENT_TIME" TIMESTAMP,
		"EVENT_STATUS" INTEGER,
		"EVENT_COMMENT" LONG VARCHAR
	)
	DATA CAPTURE NONE;

ALTER TABLE "EVENTS" ADD CONSTRAINT "EVENTPK" PRIMARY KEY
	("EVENT_ID");