--<ScriptOptions statementTerminator=";"/>

INSERT INTO EMPLOYEE ("FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "BIRTH_DATE", "HIRING_DATE", "ROLE_NAME", "COMMENTS")
  VALUES ('PEDRO', 'JUAREZ', 'ROMERO', '1980-10-31', '2015-01-01', 'Sr. Developer', 'IT Area');

  INSERT INTO EMPLOYEE ("FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "BIRTH_DATE", "HIRING_DATE", "ROLE_NAME", "COMMENTS")
  VALUES ('CAMILO', 'GUTIERREZ', 'MORENO', '1988-06-15', '2015-02-01', 'Jr. Developer', 'IT Area');

  INSERT INTO EMPLOYEE ("FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "BIRTH_DATE", "HIRING_DATE", "ROLE_NAME", "COMMENTS")
  VALUES ('ALEJANDRO', 'CASTRO', 'PASOS', '1979-09-23', '2015-03-01', 'Project Manager', 'Projects Area');