--Script for trigger creation

CREATE TRIGGER "EMPLOYEE_CREATE" 
	AFTER INSERT ON "EMPLOYEE"
	REFERENCING NEW AS NEW_EMP
	FOR EACH ROW
	INSERT INTO "EVENTS" (OBJECT_KEY, OBJECT_VERB, OBJECT_NAME, EVENT_PRIORITY, EVENT_TIME, EVENT_STATUS, EVENT_COMMENT)
       VALUES (NEW_EMP.EMPLOYEEID, 'CREATE', 'EMPLOYEE', 1, (SELECT current timestamp FROM sysibm.sysdummy1), 0, 'EMPLOYEE CREATED');

CREATE TRIGGER "EMPLOYEE_DELETE" 
	AFTER DELETE ON "EMPLOYEE"
	REFERENCING  OLD AS O
	FOR EACH ROW

INSERT INTO "EVENTS" (OBJECT_KEY, OBJECT_VERB, OBJECT_NAME, EVENT_PRIORITY, EVENT_TIME, EVENT_STATUS, EVENT_COMMENT)
       VALUES (O.EMPLOYEEID, 'DELETE', 'EMPLOYEE', 2);

CREATE TRIGGER "EMPLOYEE_UPDATE" 
	AFTER UPDATE ON "EMPLOYEE"
	REFERENCING  NEW AS N
	FOR EACH ROW

INSERT INTO "EVENTS" (OBJECT_KEY, OBJECT_VERB, OBJECT_NAME, EVENT_PRIORITY, EVENT_TIME, EVENT_STATUS, EVENT_COMMENT)
       VALUES (N.EMPLOYEEID, 'UPDATE', 'EMPLOYEE', 3);
